# 监控

## 错误的捕获

错误一般有：

- [`js` 代码执行](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error)
- Promise
- 资源加载
- 网络请求
- 跨域脚本执行

js 代码执行时异常
js 代码执行异常，是我们经常遇到异常。
这一类型的异常，又可以具体细分为:

### `js` 代码执行

一般通过 try...catch 语句块来捕获这一类型异常，也可以通过 window.onerror = callback 或者 window.addEventListener('error', callback) 的方式进行全局捕获。

### Promise

在使用 promise 时，如果 Promise 被 reject 但没有做 catch 处理时，就会抛出 promise 类异常。
`Promise.reject(); // Uncaught (in promise) undefined`

Promise 类型的异常无法被 try...catch 捕获，也无法被 window.onerror = callback 或者 window.addEventListener('error', callback) 的方式全局捕获。针对这一类型的异常, 我们需要通过 window.onrejectionhandled = callback 或者 window.addListener('rejectionhandled'， callback) 的方式去全局捕获

### 静态资源加载

资源链接失效，就会提示资源类型加载如异常。

```html
<img src="test.png" />
```

// GET test.png net::ERR_FILE_NOT_FOUND

可以通过 window.addEventListener('error', callback, true) 的方式进行全局捕获

> window.onerror = callback 的方式无法捕获静态资源异常，资源类型错误没有冒泡，只能在捕获阶段捕获，而 window.onerror 是通过在冒泡阶段捕获错误，对静态资源加载类型异常无效

### 接口请求

在浏览器端发起一个接口请求时，如果请求的 url 的有问题，也会抛出异常。不同的请求方式，异常捕获方式也不相同:

1. fetch。
我们可以通过 fetch(url).then(callback).catch(callback) 的方式去捕获异常。
2. xhr 实例发起
   1. xhr.open 方法执行时出现异常，可以通过 window.addEventListener('error', callback) 或者 window.onerror 的方式捕获异常
   2. xhr.send 方法执行时出现异常，可以通过 xhr.onerror 或者 xhr.addEventListener('error', callback) 的方式捕获异常。

### 跨域脚本执行异常

当项目中引用的第三方脚本执行发生错误时，会抛出一类特殊的异常。这类型异常和我们刚才讲过的异常都不同，它的 msg 只有 'Script error' 信息，没有具体的行、列、类型信息。
之以会这样，是因为浏览器的安全机制: 浏览器只允许同域下的脚本捕获具体异常信息，跨域脚本中的异常，不会报告错误的细节。
针对这类型的异常，我们可以通过 window.addEventListener('error', callback) 或者 window.onerror 的方式捕获异常。
当然，如果我们想获取这类异常的详情，需要做以下两个操作:

1. 在发起请求的 script 标签上添加 crossorigin="anonymous";
2. 请求响应头中添加 Access-Control-Allow-Origin: *；

## 性能

https://web.dev/i18n/zh/custom-metrics/

## sentry

数据类型：

errors, exceptions, crashes, transactions

transaction span event
